-- 코드를 입력하세요

# USER_ID - USER_ID 

SELECT
    YEAR(o.SALES_DATE) AS YEAR,
    MONTH(o.SALES_DATE) AS MONTH,
    u.GENDER AS GENDER, 
    COUNT(DISTINCT u.USER_ID) AS USERS
FROM ONLINE_SALE o
LEFT JOIN USER_INFO u ON o.USER_ID = u.USER_ID
WHERE u.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER ASC